### ISSUE TITLE
DSGM Fade In and Out

### ISSUE THREAD

**Issue by BaronKhan** [CTurt/dsgmLib#4]
In DSGM_FadeOutToBlack() and DSGM_FadeOutToWhite(), my understanding is that the function checks if brightness==0 and then performs the while loop, but this may not be the case as the user may want to manually set the brightness at some point using DSGM_SetBrightness() to something other than 0 during the game. The if statement should not be here in this case, just perform the while loop normally (why restrict the user to only fade at brightness 0?).

Also, why is the brightness read using DSGM_BOTTOM? Shouldn't it be 'screen'? I thought DSGM_BOTTOM is a preprcessor macro for 0 (bottom screen), no?

(Also, nice to see you again. Hope everything is well.)

**Comment by CTurt** [comment]
Thanks for the report, Baron!

I've fixed this as of commit: https://github.com/CTurt/dsgmLib/commit/4e57cf65f93c8c585ddc558945555105fc3c009d
